### ISSUE TITLE
How to Contribute

### ISSUE THREAD

**Issue by hmzq-dev** [Ridwan-AI/caiefinder-docs#1]
Hey, I am a student using CaieFinder, and I have found it to be quite useful. However, I would also like to see some additional features / improvements to make the overall user experience more cohesive. So, is there any way I can contribute to this project?

**Comment by Ridwan-AI** [comment]
Yes of course! We can contact on discord, mine's @ridwanai

**Comment by hamza-qadir0** [comment]
Alright, sent you a friend request.
